### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#115]
this.

**Comment by jankowiakmaria** [comment]
I've just found https://github.com/skywinder/Github-Changelog-Generator 
list with alternatives: https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives

**Comment by matteofigus** [comment]
Nice. I would like to use a node one in order to be binded to the grunt version task. [This](https://github.com/streetlight/grunt-github-changes) looks promising

**Comment by jankowiakmaria** [comment]
@matteofigus as changelog generators use tags to create proper changelog I thought of using https://github.com/rubenv/grunt-git#the-gittag-task as a part of 'version' grunt task. What do you think? (Next step would be to add tags to already released versions and then changelog generation)
