### ISSUE TITLE
Convert to Hapi

### ISSUE THREAD

**Issue by andyroyle** [opentable/oc#121]
let the flame wars, begin!

**Comment by matteofigus** [comment]
:beers: 
![YES](http://img.pandawhale.com/post-30705-morpheus-is-fighting-neo-gif-H-3vI0.gif)

**Comment by nickbalestra** [comment]
@andyroyle any specific reason for this? Would love to hear your points in this direction

**Comment by matteofigus** [comment]
@nickbalestra I think the goal is to re-use existing Hapi modules that we use at OpenTable, but we need to take care of 2 things:
1) This is just a nice to have, very low priority and not required - probably we can close and re-open later
2) Hapi is quite opinionated about supporting new versions of node, and OC@0.X.X still supports 0.10.X (but won't in OC@1.X.X) - extra reasons probably to close this and re-open later

**Comment by matteofigus** [comment]
I'm gonna close this and in case re-open later. This is not important - also need to stop supporting node 0.10 in order to get to hapi - which is gonna happen in OC v1 anyways
