### ISSUE TITLE
Change option parser for cli

### ISSUE THREAD

**Issue by jankowiakmaria** [opentable/oc#135]
as the one currently used (https://github.com/harthur/nomnom):
- is not maintained: https://github.com/harthur/nomnom#deprecation-notice
- has a lot of bugs

I can work on it - any recommendations for parser?
https://github.com/tj/commander.js?

**Comment by matteofigus** [comment]
Yes I like commander, it would be cool if you could pick up this @jankowiakmaria

**Comment by jankowiakmaria** [comment]
👍

**Comment by nickbalestra** [comment]
@jankowiakmaria @matteofigus I used [minimist](https://github.com/substack/minimist) for the [cycle.js CLI](https://github.com/cyclejs-community/create-cycle-app) and I like it (is about 1/5th of the size of commander, and does the job.)

**Comment by jankowiakmaria** [comment]
Thanks @nickbalestra 
I'll try to work on it during the next 20% time.

**Comment by jankowiakmaria** [comment]
I was able to start working on that ("cli" branch) - I actually decided to use [yargs](https://github.com/yargs/yargs) - I didn't like commander for some reason.
