### ISSUE TITLE
Client-side retry mechanism optimisations

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#136]
It would be cool for the client-side client to be able to:
* [ ] Optionally set a maximum number of retries
* [ ] Optionally set a parameter to report the retry number (http://server/component/...?__oc_Retry=2)

**Comment by andyroyle** [comment]
exponential backoff as well?

**Comment by matteofigus** [comment]
That would be cool. ATM I think retries happen just every 5 seconds (and the number is configurable)
