### ISSUE TITLE
Client-side components dependencies

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#137]
So, we can nest components nicely, and this is good.
Now next challenge is to put a component in the DOM, and before the rendering verifying its components' dependencies are satisfied first.

Let's imagine somebody would have the idea of having a `js` component, and let's imagine we have a `header` component that requires the `js` to be rendered first.
If we do server-side rendering all is gonna be good and in the right place, but what if we have client-side rendering (as failover perhaps)? So it would be cool if header would have in his definition:
```js
...
  "oc": {
    ...
    "dependencies": {
      "js": "0.6.X"
    }
}
```
So that when the client-side rendering of the header happens, the dom is scanned in order to find a js component, and it is shown only when the dependency is rendered.

In order to achieve this we would need, on the client, probably, to have an event fired when any component is rendered, so that components with dependencies can subscribe to this stream of events.
For server-side rendered components, instead, we would probably need to bring to the client-side the information about the name and the version, in case the component is rendered without container.
Maybe something like
```html
<!-- oc-component name="js" version="1.2.5" -->
```

This is actually required for achieving 100% client-side rendering failover, where we could have many components depending on each other and have mixed rendering strategies (some server-side renderings succeed and some fail going back to the client)

@andyroyle what do you think?

**Comment by andyroyle** [comment]
makes sense to me.

**Comment by matteofigus** [comment]
This is not required anymore for two reasons.
1) It is now possible to see if a component is in the page already via `oc.renderedcomponents` 
2) That doesn't mean the component is ready. `oc.events` now allows component to declare readiness and other components can subscribe to ready events.
