### ISSUE TITLE
Remove old stuff

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#146]
Looks like some stuff was a good idea at the beginning, not sure we really need some stuff anymore:

- [x] oc link (as consumer, you do oc link header@1.2.3 to add it to local oc.json file)
- [x] oc unlink (as consumer, you remove the linked component from oc.json file)
- [x] oc info (to see info about a linked component and in case suggest upgrade)
- [x] oc ls (to see all components for linked registry - we have the web interface now for that)

So, democratically, I am gonna ask top 4 contributors and my vote is gonna be counted only if is gonna be a tie. Please vote for each one until Friday night replying here for keeping or killing each one of those functionalities.

@jankowiakmaria @andyroyle @federicomaffei @tpgmartin

**Comment by federicomaffei** [comment]
@matteofigus - Good idea to involve contributors. Personally haven't been a huge user of the cli part so far, so a bit difficult for me to make a call.
What are your concerns about those commands? Maybe the fact that they are not useful enough and/or the state of the code (e.g. not tested, not updated as the rest, not enough time to maintain them, etc.)?

**Comment by matteofigus** [comment]
The concerns are that if something is not needed, it should be killed asap to keep code smaller and more maintainable. OC is growing and I believe that if we kill what we don't need anymore we can focus on the new stuff.

**Comment by andyroyle** [comment]
Sorry I'm a bit late to the party.

I say kill them all.

We can always add stuff back if necessary

**Comment by jankowiakmaria** [comment]
:+1: (sorry for late response)

**Comment by federicomaffei** [comment]
Let's kill 'em all @matteofigus!

**Comment by matteofigus** [comment]
Good :+1:
