### ISSUE TITLE
Issue setting up registry

### ISSUE THREAD

**Issue by navamgupta** [opentable/oc#161]
I followed the documentation for registry setup and got myself a test s3 bucket, updated the index.js with the relevant information (Attached index.js content) 
Now when i run it using node index.js 

I see the following message -

cache init
Connecting to library: open-components/components
components_cache_empty

It seems to not do anything after that. Would be great if someone can explain what the error is exactly? Apologies I have not yet started going through the code to debug this, will do soon :)

I will play with the bucket setup later tonight and update here. I have a feeling it could be an access issue.

Thanks,
Navam
[index.txt](https://github.com/opentable/oc/files/70392/index.txt)

**Comment by matteofigus** [comment]
Hi Navam!

On a first look, it seems like it is trying to connect to the s3 bucket for the first time and it is having problems. The error is totally not the right one, so marking this as bug.

Something that seems wrong in the configuration is the s3 region: it has to be the region identifier, not the name: so for Northern California should actually be "us-west-1" I think. 
[Regions and endpoints in AWS docs](http://docs.aws.amazon.com/general/latest/gr/rande.html)

**Comment by navamgupta** [comment]
Haha that was the problem.

Thanks,
Navam

**Comment by matteofigus** [comment]
No worries. 

Issues for questions are fine, we also have the gitter chat: https://gitter.im/opentable/oc

**Comment by matteofigus** [comment]
Just opened #162 to keep track of this error message. Closing this in the meanwhile as solved.
