### ISSUE TITLE
Client-side script should keep licences or keep link to them

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#181]
For head.js + OpenTable's MIT.

**Comment by andyroyle** [comment]
can we just minify them into the source?

**Comment by matteofigus** [comment]
Basically oc-client.min.js = uglify(head.js + oc-client.js + oc.clientVersion=<version>)

To make that we should
* Keep the head license on top after the minification + the oc-client (supported by uglify but somehow I tried and it seems to not work)
* OR (preferred as smaller) put the licences anywhere and keep in the minified file the link (something like this on top // Licenses: https://github.com/opentable/oc/CLIENT_LICENSES.md)
