### ISSUE TITLE
oc dev looks for local oc.json but could do better than that

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#219]
Basically,  when 'oc-components' is a folder of components, 
* `cd oc-components && oc dev . 3030` works (if oc.json is there)
* just `oc dev oc-component 3030` doesn't (because it looks for oc.json in that folder).

The cli should try to look for oc.json inside the folder and then in the parent if not found.

**Comment by tpgmartin** [comment]
@matteofigus I'd like to be assigned to this issue

**Comment by matteofigus** [comment]
:+1:
