### ISSUE TITLE
OC plugin to render nested components on the server-side

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#224]
When rendering nested components on the server-side, an unnecessary network trip is required to make extra requests to the registry itself.
The ideal solution for optimally approaching to this scenario would be to have a plugin to render nested components using exposed registry internals to do the rendering via the same instance. 

The api for a `server.js` file should be something like this:
```js
module.exports.data = function(context, callback){
  var nestedComponents = [
    { name: 'component', parameters: { 'hello': 'world' }},
    { name: 'component2', parameters: { 'hello': 'world' }}
  ];
  context.plugins.renderComponents(nestedComponents, function(err, components){
    callback(null, components);
  });
};
```
The plugin should have the same API as [the node.js client's `renderComponents` method](https://github.com/opentable/oc/tree/master/client#clientrendercomponentscomponents--options-callback) - but it should do the rendering without making an extra request to itself.

**Comment by matteofigus** [comment]
This depends on #223 and #185

**Comment by navamgupta** [comment]
Guys,

Whats the plan/priority for this feature? Teams at Chegg are really looking forward to it since half of us are on PHP making it interesting to do rendering part server side.

Thanks,
Navam

**Comment by matteofigus** [comment]
Hi @navamgupta I think we haven't started yet with this. Will try to prioritise it.
