### ISSUE TITLE
Make OC browser client AMD compatible

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#226]
So that it can be used with any AMD loader

**Comment by Hobbit71** [comment]
+1 from me for this

**Comment by matteofigus** [comment]
Not sure I have so much time for working on this. Would you be able to help @Hobbit71? 
Or perhaps @nickbalestra / @mattiaerre / @tpgmartin ?

**Comment by Hobbit71** [comment]
Let me fork the code and take a look @matteofigus. Will see if I can do it over the weekend.

**Comment by matteofigus** [comment]
Thanks. The code is mostly [here](https://github.com/opentable/oc/tree/master/src/components/oc-client). 
The `grunt test-local` task should run the tests for that and `grunt build` should build the package. 
Let me know if you have any issues.
I think that piece of code kind of works but would need some love to be cleaned up a bit 👍

**Comment by Hobbit71** [comment]
Thanks @matteofigus for the info, already got the code in front of me. Will ping you if I hit anything major. Looking good so far.
