### ISSUE TITLE
Loading dependencies in particular order and error out

### ISSUE THREAD

**Issue by iroy2000** [opentable/oc#275]
I'm trying to load my scripts in particular order ...

```
<script>
    window.oc = window.oc || {};
    oc.cmd = oc.cmd || [];

    oc.cmd.push(function(oc) {
        oc.require('common', '//d16gdqpunp364y.cloudfront.net/assets/common-8c7dbd1faf1bda861xxx.js', function(common) {
	        oc.require('app', '//d16gdqpunp364y.cloudfront.net/assets/app-8c7dbd1faf1bda861xxx.js');
        });
    });

</script>

```
Seems like it is working,  but am I doing it correctly ? 

However, I will see the following message when I'm doing that ...

![screen shot 2016-07-21 at 7 11 04 pm](https://cloud.githubusercontent.com/assets/487520/17044647/edc10b2e-4f76-11e6-9538-b7e295deaca9.png)

So the question is **how to correctly load dependencies files in particular order in OC** ??

Thanks

**Comment by matteofigus** [comment]
Hi @iroy2000 I suspect `oc.require` wants a mandatory callback param, which you are not providing on the second call. I'll do a test do confirm.

**Comment by iroy2000** [comment]
@matteofigus thanks, you are right, the callback param is mandatory.  Ok, closing it.

**Comment by iroy2000** [comment]
Btw, do you think I served my "build" assets and upload my stuff to S3 in my build system and then put them into OC template, do you think it is okay?

Currently what I have is
1) create a unique name ( with hash ) every build 
2) upload to S3 in my build
3) I just manually copy the "cdn url" of my assets and use it in OC template

So in that sense, I used OC's registry for versioning so far, is that a good use case ?

I want to know what OC did at the back compare to my build process. 

Thanks

**Comment by matteofigus** [comment]
That's a great question @iroy2000 - you know what, I'm gonna write a wiki page for documenting a bit better what the publish process looks like. Another thing may be to create a FAQ wiki page (you're not the first that asked this question).

Finger in the air, sounds like your approach is ok. OC will need anyways s3 to publish its own components - and the bucket can be shared with the other assets (but that's up to you).

**Comment by matteofigus** [comment]
And here we go! https://github.com/opentable/oc/wiki/F.A.Q#i-already-use-s3-to-save-my-assets-via-a-consolidated-build-pipeline-can-i-reference-this-files-from-my-oc-components

Closing this because of the title - if you want we can continue the conversation on gitter!

Thanks for your contribution
