### ISSUE TITLE
OC events handler should support .off()

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#296]
In order to allow unsubscribe from events. Requested by @munkychop

**Comment by matteofigus** [comment]
Turns out this was already implemented but not documented.

Updated the docs: https://github.com/opentable/oc/wiki/Browser-client#oceventsreset

**Comment by ricardo-devis-agullo** [comment]
What its implemented it's the `reset` method, which is closer to [removeAllListeners](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname). Could we have an .off method that resembles more the o[ff](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname) where you pass also the eventName and callback?

**Comment by matteofigus** [comment]
@ricardo-devis-agullo I would be in favour of that. Would you be able to do a Pull Request?

**Comment by ricardo-devis-agullo** [comment]
Yes, I can :)
