### ISSUE TITLE
Migrate Jade to Pug

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#298]
This will fix #297 and in addition will allow some cleanup in terms of the npm-shrinkwrap overrides.

**Comment by nickbalestra** [comment]
Note: once we have the plugin template plugin system in place, create a pug template plugin to support it.

**Comment by matteofigus** [comment]
I am closing this, because the new plan is to instead remove the jade template from the base templates with a new breaking change in the future. In that scenario, people will be able to just use the new template for pug.
