### ISSUE TITLE
Unable to require nested paths

### ISSUE THREAD

**Issue by matthewdavidson** [opentable/oc#322]
The following code in `server.js` does not work, even though `react-dom` is listed as a dependency in 
the components `package.json`:
```js
var ReactDOMServer = require('react-dom/server');
```
I get the following error:
```sh
Packaging components...an error happened while packaging <component_path>: 
Missing dependencies from package.json => ["react-dom/server"]
```

Here is a reproduction of the issue: https://github.com/matthewdavidson/oc-nested-requires-bug

I'm happy to attempt a PR unless you have any major objections :).

**Comment by matteofigus** [comment]
Hi @matthewdavidson thanks for submitting the issue, good catch!

Definitely I bug I would like to be fixed! I would love a PR for that 👍
