### ISSUE TITLE
Custom cache headers set by one component could appear as a cache headers for another

### ISSUE THREAD

**Issue by ivan-dimitrov-skyscanner** [opentable/oc#327]
@matteofigus 

We found a bug introduced in #326 - the problem is on line 30 in get-component.js file. There we introduced responseHeaders variable but this is in a outerer context than it should be. Because of this every invocation of render sees one and the same variable and every component inherits the headers introduced by former ones.
The fix is to move the responseHeaders variable inside renderer function.

I'm basically having the fix and am working on a regression test to validate it. Perhaps tomorrow I'll do a PR.

**Comment by matteofigus** [comment]
Ok, thanks. We haven't tested this version yet but planning to do next week. In case I'll wait for the fix!

Thanks
