### ISSUE TITLE
Drop IE8

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#338]
I wonder if we still care about it. There is a lot of code in the client-side client due to the fact that IE8 and IE9 need polyfills to make AJAX reqs + broken support for custom elements (IE8 only).
This only impacts client-side rendering as server-side rendering should be browser independent. 

What do you think @nickbalestra @mattiaerre @ivan-dimitrov-skyscanner @matthewdavidson @navamgupta ?

The reason I ask is to also facilitate decision making related to #281

**Comment by matthewdavidson** [comment]
Hey @matteofigus thanks for the consideration. Happy with dropping ie8, but let me dig out some numbers for ie9 usage this afternoon.

Regardless, ie9 ajax support _should_ be relatively light weight no? Vanilla js example:
```js
var request = new XMLHttpRequest();
request.open('GET', '/my/url', true);

request.onload = function() {
  if (request.status >= 200 && request.status < 400) {
    // Success!
    var resp = request.responseText;
  } else {
    // We reached our target server, but it returned an error

  }
};

request.onerror = function() {
  // There was a connection error of some sort
};

request.send();
```

Source: http://youmightnotneedjquery.com/#request

**Comment by nickbalestra** [comment]
+1

**Comment by matteofigus** [comment]
Ok, after this discussion I'll keep this only for removing IE8 support, we'll keep IE9 for now.
