### ISSUE TITLE
Change/Extend the OC Client to perform GET instead of POST when requesting one component

### ISSUE THREAD

**Issue by ivan-dimitrov-skyscanner** [opentable/oc#342]
That's in connection with the custom headers introduced recently. 
In order to benefit from any intermediate caches we need to perform GET requests (component by component). In case of bulk requests we can still go with POST but in case the microsite is built to anticipate it then doing only GET requests with the the appropriate caching could bring a log of speed and offload the registry.

So the general idea is either to:
- change the OC Client so that invoking renderComponent(...) will trigger a GET request
or
- introduce a new method renderComponentGet(...) to do this.

**Comment by matteofigus** [comment]
I'm ok with doing get for renderComponent() - the underlining request type should be of no interest for the consumer and shouldn't break any existing contract ;)

In case of the POST, perhaps as a separate PR for a future issue, I think it would be still nice to get the same capability by extending the response:
```js
[{
  status: 200,
  response: ...,
  headers: ...
}]
```
