### ISSUE TITLE
Config routes containing same prefix as components are never hit

### ISSUE THREAD

**Issue by debopamsengupta** [opentable/oc#350]
Hi @matteofigus , just a small issue here
In my config, I have something like
```
prefix: '/abc/',
routes: [{
        route: '/abc/<some_custom_route>',
        method: 'get',
        handler: function(req, res) {
           //return data
        }
    }]
```
But this route is never hit as the routes added via config are registered after the default OC component routes
https://github.com/opentable/oc/blob/master/src/registry/router.js#L54

If you agree, more than happy to make a PR for a fix :)

**Comment by matteofigus** [comment]
Hi, thanks for your submission.

This is all for enforcing simplicity and keeping the API clear and easily understandable. In our case we have our prefix like `//componentsurl.com/components/...` and have all the custom routes outside of the prefix: `//componentsurl.com/custom-route` and it works well for us. I guess this is the recommended way and it is not very well documented (and not nicely handled as the API starts without any warning or error).

Consider that in the current setup you can still extend the components' namespace, for instance adding a `/:component/:version/hello` which would automatically created for each component.

If you are still designing your API (as I guess you are given you are now taking care of the extra endpoints) would be too much of a compromise to follow the same convention? I mean having an extra prefix for the components and keep the custom routes one level down or with a different prefix. If that's ok for you, we can still keep the issue opened to clarify the docs and return an error in case somebody tries to add a route to the same components' namespace.

**Comment by debopamsengupta** [comment]
Hi, the namespace separation makes sense and agreed should return an explicit error if possible :)

**Comment by matteofigus** [comment]
Ok, I'll keep this issue opened to update docs and error handling ;)

**Comment by matteofigus** [comment]
Wiki updated: https://github.com/opentable/oc/wiki/Registry
