### ISSUE TITLE
How to run in docker?

### ISSUE THREAD

**Issue by demaniak** [opentable/oc#354]
Does anybody have a sample Dockerfile (or instructions) on how to get this running in a Docker container?

So far OC refuses to start in a Ubuntu-based container (Node 7.5.0). Running outside the container works fine.

The error message is: `Registry not started: components_list_get`

**Comment by matteofigus** [comment]
Hi @demaniak the registry needs to be instantiated in a node app via requiring it as dependency and setting all the configuration. You can find more info in the wiki. If you are already doing it, still,

1) Take in mind that node 7 is still not supported. Not sure there may be issues there but it's still not covered by our test suites. Definitely something we can improve on our side
2) The error message sounds like there is a connection problem with S3. Is your docker container able to access the public internet (to access aws's api)? Also, how are you passing the s3 credentials in the registry instantiation? If via environment variables, are you ensuring your container gets them?

We use Docker as well for releasing this at OpenTable and the image is just a quite basic Ubuntu + node 6 + a couple of internal tools and it just starts the app by `npm start`, so nothing special there.

In case you don't solve, can you share your input js file for starting the registry? In case, I can review.

**Comment by demaniak** [comment]
Thank you for the reply @matteofigus . 

I am also a bit puzzled by this - there is nothing glaringly obviously wrong.
Some test `wget` requests to S3 (ran outside the container, and inside the container) seems to work fine.

Will go back and verify some items, and downgrade node.
Will post results here as soon as possible.

**Comment by matteofigus** [comment]
I opened a PR for testing node 7 #362 and I confirm something is red there. We'll prioritise some work to get it green ;)

**Comment by demaniak** [comment]
Thank you for the reply @matteofigus . 

I am also a bit puzzled by this - there is nothing glaringly obviously wrong.
Some test `wget` requests to S3 (ran outside the container, and inside the container) seems to work fine.

Will go back and verify some items, and downgrade node.
Will post results here as soon as possible.

**Comment by matteofigus** [comment]
@demaniak we made some fixes and made node 7 green. If you upgrade to the latest version that may improve things 👍

**Comment by matteofigus** [comment]
This doesn't seem to be an issue anymore. In case, you can reopen.
