### ISSUE TITLE
Wiki Wide Open!

### ISSUE THREAD

**Issue by adamgoose** [opentable/oc#378]
I created [this revision](https://github.com/opentable/oc/wiki/F.A.Q/_compare/5ef1fdff6815fe42a82fed8a1cada16620f0ff33...3478128e299836339262668cbb0333203346e637) to the wiki, intending (rather hoping) for it to be submitted via PR. I apologize for making a change without requesting permission, but hopefully it's acceptable.

Meanwhile, it might be wise to adjust the permissions on this repo's wiki.

**Comment by matteofigus** [comment]
Thanks, I adjusted the permissions 👍 

I think your submission is very good, thanks for your help!
