### ISSUE TITLE
Supporting Minio (or other non-AWS S3 solution)

### ISSUE THREAD

**Issue by adamgoose** [opentable/oc#379]
I'd like to use OC with [minio](https://minio.io). Since it's S3-compliant, it could easily be possible by allowing configuration of the S3 API endpoint (as opposed to the AWS endpoints). Minio also has a requirement of using v4 of the S3 signature algorithm. 

```
var s3  = new AWS.S3({
          accessKeyId: 'YOUR-ACCESSKEYID' ,
          secretAccessKey: 'YOUR-SECRETACCESSKEY' ,
          endpoint: 'http://127.0.0.1:9000' ,
          s3ForcePathStyle: 'true', // needed with minio?
          signatureVersion: 'v4'
                                });
```

http://docs.minio.io/docs/how-to-use-aws-sdk-for-javascript-with-minio-server

**Comment by adamgoose** [comment]
Looks like a conditional update to [these lines](https://github.com/opentable/oc/blob/master/src/registry/domain/s3.js#L17-L22) would do the trick!

**Comment by matteofigus** [comment]
Hi, I made actually a bit of research. OC uses file-based ACLs to secure some files, and unfortunately minio doesn't seem to support that (yet): https://github.com/minio/minio/blob/77a192a7b560f4f7c933280536231996cfb39414/docs/minio-limitations.md#list-of-amazon-s3-object-apis-not-supported-on-minio

I think minio looks like a great project and perhaps it would be possible to ask for that feature. In any case, I would be happy to accept a PR for OC to make additional S3 parameters configurable, such as endpoint, signatureVersion, etc. Would you be able to try?

Only thing, I removed the minio suggestion from the wiki until we ensure it allows full integration - we can add it later.

**Comment by adamgoose** [comment]
Sure thing! Once I dive in a bit deeper, I'll see if I can get a PR made.

**Comment by matteofigus** [comment]
I am closing this at the moment. We can reopen in case we still are interested.

**Comment by danlaney** [comment]
I was just researching this aspect of S3 API support.  We have some fine-grained access control requirements and are looking for open source solutions that might form a back-end for our tools.  We have a draft requirements document [here](https://github.com/DOE-Workflows/SDM-requirements)

**Comment by kmcrawford** [comment]
I have created a PR #662 against this issue.  I created minio in my kubernetes cluster (on GCP) with no external access, so this should minimize security concerns.

The plan would be that it supports the following s3 config.  I could create a minio flag and set the s3ForcePathStyle & s3ForcePathStyle in the code.  But since these are valid s3 options, figured I would leave them configurable.  Thoughts?

s3: {
    key: 'YOUR_KEY',
    secret: 'YOUR_SECRET_KEY,
    endpoint: 'http://minio.default.svc.cluster.local:9000',
    path: 'http://minio.default.svc.cluster.local:9000/YOUR_BUCKET/',  //Now supporting protocol 
    s3ForcePathStyle: 'true',
    signatureVersion: 'v4',
    componentsDir: 'components',
    bucket: 'YOUR_BUCKET',
  },

**Comment by kmcrawford** [comment]
I have closed my pr due to that fact that I now understand that oc requires most files to be public.
