### ISSUE TITLE
oc publish using version 0.34.8 to an S3 bucket ignoring the folder structure

### ISSUE THREAD

**Issue by ggehlot1980** [opentable/oc#386]
oc version - 0.34.8
os - Windows 10
I was trying to do an oc publish to an S3 bucket. My project gets published, but without any folder structure and all the file names are modified to include the folder names with backslash. So I get a flat structure for my project due to which the resources being referenced from my files becomes unavailable. This issue has been observed on MAC too.

**Comment by matteofigus** [comment]
Thanks @ggehlot1980 

I am trying to understand if this is a Windows 10 problem as I remember as similar issue a while ago: https://github.com/opentable/oc/issues/30

If you see the same issue from a mac it may be unrelated. We use macs to publish components every day so the issue may be different. Either component related or registry related.

Just to be sure. When you say `publish to an S3 bucket` - you mean you are using the oc cli to publish and you are actually publishing to an OC registry right?

**Comment by ggehlot1980** [comment]
Yeah I am using the oc cli to publish (oc publish <name>)and I am publishing to the oc registry only. My oc registry is linked to the the S3 bucket.

**Comment by matteofigus** [comment]
Oh, I see, so the registry itself being running on Windows may actually be related to #30

**Comment by matteofigus** [comment]
Ok, I confirm that running a registry instance in windows and publishing to it the S3 upload is broken.

<img width="1440" alt="screen shot 2017-02-24 at 16 33 55" src="https://cloud.githubusercontent.com/assets/1789893/23311743/1313d62a-faaf-11e6-886e-8ab561be50eb.png">

When instead publishing from windows to a linux registry, I see an error: "package is not valid".

So, I believe the packaging phase that creates/unpackages the tar.gz file has more than one problem on windows machines.

**Comment by matteofigus** [comment]
@ggehlot1980 this should be now fixed. Can you please retry by ensuring both Registry and CLI run with the latest version I just published: 0.35.5
