### ISSUE TITLE
Static js needs to be transpiled before minification

### ISSUE THREAD

**Issue by nickbalestra** [opentable/oc#409]
As we don't transpile to es2015 completely, uglify will trow. 
Proposed solution: swap uglify with [babili](https://github.com/babel/babili)

**Comment by mattiaerre** [comment]
@nickbalestra let me know if you would like to pair on this

// cc @matteofigus

**Comment by debopamsengupta** [comment]
Hi, was this fixed by https://github.com/opentable/oc/pull/411 ?

**Comment by matteofigus** [comment]
No @debopamsengupta that was for server.js, this is for client-side javascript. I actually was talking about this with @nickbalestra and I'm not sure we'll use babili. For sure we need to place a babel compilation as pre-minify step

**Comment by matteofigus** [comment]
Reopening because of #420
