### ISSUE TITLE
Express app error handling for registry

### ISSUE THREAD

**Issue by debopamsengupta** [opentable/oc#424]
Hi @matteofigus just thinking if it'll be good to have some overall error handling for the registry express app, like https://expressjs.com/en/guide/error-handling.html ?

We just ran into a situation where our `publishValidation` function was throwing a runtime error while publishing a component, but CLI still responds with a "publish succeeded" message.

OC version --> 0.36.13

**Comment by matteofigus** [comment]
Hi @debopamsengupta have you looked at https://github.com/opentable/oc/wiki/Registry#registry-events - the registry fires various kinds of error and you can log them by hooking them to any logging infrastructure.

In regards of the publishValidation, that sounds weird. It should show an error in the CLI if the publish failed? Unless there is some specific unhandled problem in the publish custom validator. Do you have some code examples to share about the validator?

Thanks

**Comment by debopamsengupta** [comment]
@matteofigus yeah it was an unhandled problem in the custom validator:
```js
const validator = (pkg) => {
    //some dodgy code that throws error
   return {
        isValid: false,
        error: 'Validation failed'
    };
} 
```

**Comment by matteofigus** [comment]
So, my take is to ensure you have testing around that, and in case error handling in the way you prefer.

When you instantiate the registry by `var registry = oc.Registry(config);` then you can access the express app by `registry.app` which then allows you to attach any middleware to express and customise as you prefer.
