### ISSUE TITLE
null values are not valid as string parameters

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#425]
This was reported by @seif. 

In short, if a component has a string parameter, and we make a POST request specifying `null` as value (which is a valid json type) the validation fails as the registry considers that not valid as string (`typeof(null)!=='string'`).

Let's remember that in JS `JSON.stringify({a: undefined}) => {}` and `JSON.stringify({a: null}) => {a:null}`.

How to solve it?
1) We can add a new type of parameter which is `stringOrNull` - this means parameter is null and then is forwarded to the component as null - current behaviour for `string` wouldn't change.
2) We can be less strict and consider `null` a valid value for `string` by leaving it as null
3) We can be less strict and more opinionated and auto-sanitise a null parameter to '' in case of `string` and 0 in case of `number`
4) We can be hacky and leave everything as is on the registry and do a sanitisation on the node.js client in order to avoid this to happen on the registry level
5) Other ideas?

I personally like 2 but I like 1 too.

**Comment by seif** [comment]
@matteofigus I prefer 2, providing null/undefined is the same as not providing any value at all from my perspective (component author saying that that param is not mandatory).

**Comment by mattiaerre** [comment]
Sorry but I couldn't resist:

https://twitter.com/iamelgringo/status/845027370864001024

// cc @matteofigus @seif

**Comment by federicomaffei** [comment]
+1 for 2 @matteofigus @seif

**Comment by jwhayes** [comment]
Option 2 sounds good to me.

**Comment by matteofigus** [comment]
I think we got a winner. I'll try to do this later 👍
