### ISSUE TITLE
function to =>

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#435]
A non critical optimisation that would be ideal for a first time contribution to OC.

Edit: Before proceding, can you please vote with 👍 or 👎

**Comment by mattiaerre** [comment]
I like arrow functions but I think this issue should be tagged as `discussion` as well; unlike `const/let` there is no general agreement whether to use arrow functions or not.

**Comment by nickbalestra** [comment]
💯  x 💯  🏹  for me!

**Comment by elboletaire** [comment]
As said in #436, eslint may also help with that, at least with callback functions:

- http://eslint.org/docs/rules/prefer-arrow-callback

**Comment by matteofigus** [comment]
I removed the discussion flag as it looks there are no objections on this. Do we have enough for proceeding with this? Specifically, 

1) All agree about the eslint rule?
2) Anyone can/wants to work on this?

**Comment by elboletaire** [comment]
I want to work on this, but I'm out for two weeks, so I leave the door open for others.

I guess that client-side files should stay without arrow functions, like with #436, as [there are some still used browsers that do not understand them (like IE 10...)](http://caniuse.com/#feat=arrow-functions).
