### ISSUE TITLE
Add Webpack config hook for server.js within a template

### ISSUE THREAD

**Issue by nickbalestra** [opentable/oc#439]
Allows templates to specify a webpack configuration file to be used for bundling the data-provider.

**Comment by matteofigus** [comment]
Yes! @matthewdavidson and friends were interested on this if I recall 👍

**Comment by nickbalestra** [comment]
We have a couple of options here.

1. template expose a `compileServer()` method that will be used instead of [package-server-script/bundle](https://github.com/opentable/oc/tree/master/src/cli/domain/package-server-script/bundle)
2. template expose a webpack configuration generator similar to [this](https://github.com/opentable/oc/blob/master/src/cli/domain/package-server-script/bundle/config/index.js#L9-L55) and we merge the generated config by relying on something like [webpack-merge](https://github.com/survivejs/webpack-merge)

- Pros of 1:  more flexibility as you could decide to use any kind of bundling system (not tight to webpack)
- Cons of 1: more work is needed for the template provider wanting to alter the bundling of the data-provider (server) as he need to set up the whole bundling pipeline
- On the other side option 2 allows for a little less flexibility as you you are stick to webpack but allows for easier of override as you could extend and override any part of the current webpack configuration.

(the getInfo method of the template should provide for both cases a new properties `compileServer` to tell the CLI if it needs to use an hook or not for packaging the server)

Would love to hear your inputs on this as I would like to start takling this 
cc @matthewdavidson @matteofigus @mattiaerre @chriscartlidge @antwhite

**Comment by matteofigus** [comment]
I like 1's flexibility and I think we could easily abstract complexity by wrapping that into some configurable npm modules. My vote goes for 1.

**Comment by nickbalestra** [comment]
Another pro for option 1, is that it will allows to completely decouple webpack/babel from the oc/cli once the whole template architecture is in place

On 11 May 2017, at 11:59, Matteo Figus <notifications@github.com<mailto:notifications@github.com>> wrote:


I like 1's flexibility and I think we could easily abstract complexity by wrapping that into some configurable npm modules. My vote goes for 1.

**Comment by nickbalestra** [comment]
The more I think about the more I'm starting to think that template should also provide a third compile method: `compileStatics`, in order to be able to properly package static assets as we are doing [here](https://github.com/opentable/oc/blob/f0412ec66076cddd6264a7b6593b6e5e607a9842/src/cli/domain/package-static-files/index.js) now

So 3 things should be dealt at a template level:
- `compileServer()`
- `compileClient()`
- `compileStatics()`

This will allow template to fully deal with packaging a template ready to be published.
Thoughts?

**Comment by matthewdavidson** [comment]
Im a fan of option 1 as well. 👍

**Comment by mattiaerre** [comment]
really interesting @nickbalestra can you provide an example here even if it's pseudo-code? I'd love to understand how you would consume these methods. Thanks.

**Comment by nickbalestra** [comment]
@mattiaerre sure! For example, `compileServer` could be used in [package-components.js](https://github.com/opentable/oc/blob/f0412ec66076cddd6264a7b6593b6e5e607a9842/src/cli/domain/package-components.js#L69) by:
1. first check `getInfo` or simply check if the template expose a `compileServer` method
2. then use it instead of the core `packageServerScript`.

For the compileClient usage you can see an example already implemented [here](https://github.com/opentable/oc/blob/2485f6a623d884af311a8e4e60f0383316dad74d/src/cli/domain/package-template.js#L30)

For `compileStatics` a similar approach will be used to bypass [this module](https://github.com/opentable/oc/tree/f0412ec66076cddd6264a7b6593b6e5e607a9842/src/cli/domain/package-static-files)

**Comment by nickbalestra** [comment]
Done in #525.

Some example that demonstrates how we brought the legacy templates to the discussed new architecture:

- jade -> [oc-template-jade-compiler](https://github.com/opencomponents/base-templates/tree/master/packages/oc-template-jade-compiler)
- handlebars -> [oc-template-handlebars-compiler](https://github.com/opencomponents/base-templates/tree/master/packages/oc-template-handlebars-compiler)
