### ISSUE TITLE
Running local instance of registry via node does not create _package folders

### ISSUE THREAD

**Issue by navamgupta** [opentable/oc#441]
**Background** : We are working on enabling developers to be able to write integration test suites for their components, to do this one of the things needed is to be able to bring up and stop a local instance of the registry.

**Code** : 
```
startRegistry: function(done) {
            registry = new oc.Registry({
                baseUrl: 'http://localhost:3030/',
                local: true,
                port: 3030,
                hotReloading: false,
                path: path.resolve('../'),
                env: {name: 'local'},
                verbosity: 1,
                discovery: true
            });
            registry.start(done);
        }
```
Pretty straight forward snippet. Note that we need discovery true so that we can use phantomJS or nightmare js or casper ... to be able to load the component in preview mode.

**Problem** : So the registry did start up but it does not generate the _package folder for the component, which means we cannot really load the component in preview mode.

Thoughts?

**Comment by matteofigus** [comment]
This is correct and current behaviour. I think that we need here an option like `package: true` to ensure the registry performs a packaging before starting. We could in alternative offer a separate command just for that but I think we don't need it yet.

I can assign myself to this - it is something I want to do for some components of mine too.
