### ISSUE TITLE
PHP Client for OC

### ISSUE THREAD

**Issue by navamgupta** [opentable/oc#442]
We talked about this on the Gitter channel. I believe we do need a PHP client and am willing to work on it in collaboration with you guys. However the first step would be requirements and interface design (which could be as simple as whatever we have for the node client) . 
Lets use this issue to formalize the requirements and start working on it :)

**Comment by matteofigus** [comment]
I think this is a great idea. Agree about using the node client's API as a starting point, it should be simple and we should be able to provide parity on the various settings.

Who wants to create a repo somewhere and start sketching out some boilerplate for the PHP library? Want me to?
Let's ensure @gtrias is on the loop as I think he wants to help.

**Comment by mattiaerre** [comment]
also @gregoryStarr was interested in helping w/ PHP

**Comment by gtrias** [comment]
I would like to help as well :)
I'll try to find a moment to start something functional.

**Comment by elboletaire** [comment]
This makes me think about the node `oc-client` in this same repo. Shouldn't we move it to another different repo? More now that other clients will be created.

**Comment by matteofigus** [comment]
@elboletaire definitely we should make the PHP client in a new repo. In fact, I asked if anyone wants to create a repo somewhere to start. If you want, I can create a new one here in the opentable org but is up to you :)

In regards of the node client, yes, we already have an issue to move the browser client to own repo first (as it's a dependency of both core and node client) - then second step will be to move node client to own repo too 👍

**Comment by elboletaire** [comment]
Oh I didn't see #438 when writing that down. Good then.

**Comment by matteofigus** [comment]
Here is the new WIP repo: https://github.com/opencomponents/oc-client-php

Should I close this now that we have a new place where to discuss this?
