### ISSUE TITLE
Request that client.get() accept array as well as object

### ISSUE THREAD

**Issue by tlhunter** [opentable/oc#491]
The `client.get()` method currently accepts an array of info about components to load and resolves an array of loaded components. This can get tricky when dynamically adding components.

Can this method be updated to also accept an object of components to load, and in the case of an object then resolve an object with the loaded components?

This is the same pattern used by the async library (see http://caolan.github.io/async/docs.html#parallel) and is super convenient to work with.

```js
  // current
  const componentArgs = [
    { name: 'x' },
    { name: 'y' }
  ];

  z && componentArgs.push({ name: 'z' });
  w && componentArgs.push({ name: 'w' });

  return ocClient
    .get(componentArgs)
    .then(components => {
      work(components[0]); // x
      work(components[1]); // y
      z && work(components[2]); // z
      w && z work(components[3]); // w
      w && !z work(components[2]); // w, starting to get confusing
    });

  // propose to also support
  const componentArgs = {
    x: { name: 'x' },
    y: { name: 'y' }
  };

  z && componentArgs.z = { name: 'z' };
  w && componentArgs.w = { name: 'w' };

  return ocClient
    .get(componentArgs)
    .then(components => {
      work(components.x); // x
      work(components.y); // y
      components.z && work(components.z); // z
      components.w && work(components.w); // w
    });
```

**Comment by maxgurewitz** [comment]
👍  👍 👍 

This will be especially useful when loading components conditional on an experiment existing.

**Comment by matteofigus** [comment]
I like this idea. @tlhunter would you be able to attempt a PR for that?

**Comment by nickbalestra** [comment]
@tlhunter we moved the client to its own repo. If you want to attempt a PR please do it [there](https://github.com/opencomponents/oc-client-node) and/or feel free to close this issue

**Comment by tlhunter** [comment]
Sorry y'all, I don't have the bandwidth to pull this off.

**Comment by nickbalestra** [comment]
No worries Thomas.
Closing this for now, whenever you want feel free to re-open this [here](https://github.com/opencomponents/oc-client-node)
