### ISSUE TITLE
Call for logos

### ISSUE THREAD

**Issue by nickbalestra** [opentable/oc#493]
Inspired by [node](https://github.com/nodejs/node/issues/37), [redux](https://github.com/reactjs/redux/issues/151) and many other awesome OS projects, would be great for OC to have a nice brand too.

Let's all make some logos, spread the voice and tag friends/designers who might want to help us with this here!

**Comment by scottarnold** [comment]
![open component](https://cloud.githubusercontent.com/assets/164147/26492751/d66e2460-41e3-11e7-9551-09d7267595e0.png)

my literal interpretation

**Comment by nickbalestra** [comment]
Woho, cool, thanks @scottarnold! 
I really like how redux ended up on the neutrino concept for their logo. I wonder what could be the core idea for OpenComponents in a similar way.

For me I guess is the ability to require immutable front-end components at runtime from an npm-like registry, dun't know yet how I could translate that into a logo. I'll try to take the weekend and come up with some ideas as well.

**Comment by ryanvannin** [comment]
Not really inspired today... I dare to say that these are less than drafts.
I'm sure someone will come up with something much, much better than these!

![opencomponents_logo_no-inspiration_superdrafts_v1](https://cloud.githubusercontent.com/assets/22136060/26498038/ecdd5488-422d-11e7-94a3-1e3136b047cf.png)
![opencomponents_logo_no-inspiration_superdrafts_v2](https://cloud.githubusercontent.com/assets/22136060/26498040/ed00e2fe-422d-11e7-8dea-2ef302b415c7.png)
![opencomponents_logo_no-inspiration_superdrafts_v3](https://cloud.githubusercontent.com/assets/22136060/26498042/ed0adde0-422d-11e7-9ee2-fdb4fe1ea361.png)
![opencomponents_logo_no-inspiration_superdrafts_v4](https://cloud.githubusercontent.com/assets/22136060/26498041/ed03e396-422d-11e7-982f-dff912040052.png)
![opencomponents_logo_no-inspiration_superdrafts_v5](https://cloud.githubusercontent.com/assets/22136060/26498039/ecfee86e-422d-11e7-9f11-97edc13d8df3.png)

**Comment by wruth** [comment]
My immediate thinking was along the lines of what @ryanvannin explores, riffing off the notion of a venn diagram intersection. Or chain links maybe. A consistency of the size of the hole in the O and the opening of the C is important I think.

**Comment by mattiaerre** [comment]
this is really cool; thank you @scottarnold and @ryanvannin for your help; I think this is going to be an important step for our platform.

**Comment by nickbalestra** [comment]
Today I found some time to play with sketch. One idea I had was to see components as building blocks, so why not trying with our favorite ones... 😎  (I've also tried to bring some more colors other then red in here, [moar colors ftw](https://images.brickset.com/colours/2016palette.png))

<img width="640" alt="screen shot 2017-06-02 at 12 03 02 am" src="https://cloud.githubusercontent.com/assets/389705/26704485/56d51706-4727-11e7-8161-b032e40a9fdb.png">

**Comment by mattiaerre** [comment]
I love this idea @nickbalestra and not only the LEGO concept but also exploring new colors: +1:

**Comment by wruth** [comment]
Agree, like this treatment @nickbalestra — the bottom two with the `oc` lockup. Not sure about the locking stubs in the white areas. The bright colors are nice, but worth more exploration regarding the combinations. I might play with the concept too if I find some time.

**Comment by gitFrey** [comment]
Did someone same moar colours?

![opencomponents-shapes-02](https://cloud.githubusercontent.com/assets/3280058/26765933/80e3b9d6-497e-11e7-9deb-ac3524a457ba.png)

I've been playing with the idea of components being buildings in a cityscape so I'll try mock that up too

**Comment by mattiaerre** [comment]
this is cool @gitFrey I can see clearly an animation here 😄 I like the colors and the font; to me the last one w/o the shapes would be a good candidate (as I am already thinking about stickers and t-shirts) but I'd love to see this idea you are talking about! good job and thanks.

**Comment by nickbalestra** [comment]
@gitFrey don't know if intended but your proposal reminded me of [those](https://images-na.ssl-images-amazon.com/images/I/61yKEqSlqWL._SL1200_.jpg), and I really dig the idea. I'll might play with it as well. Keep it up!

**Comment by gitFrey** [comment]
@nickbalestra nice, yes kind of, especially if you think of those shape blocks as a child's toolbox! I think a lot of tech logos are quite serious, so think it's nice to bring some fun back in. Having the shapes there was the idea they were the components, and they can be merged to create new ones.

**Comment by nickbalestra** [comment]
I totally agree as that also imply some very important aspect: "easy to use"!, "fun to use/DX"

**Comment by gitFrey** [comment]
My cityscape idea (buildings are components, crane is the 'middleman', cityscape is the app)
![cityscapes_artboard 5](https://user-images.githubusercontent.com/3280058/26980187-4d14b02a-4d29-11e7-8b5d-3cffa8b02f32.png)
![cityscapes_cityscape](https://user-images.githubusercontent.com/3280058/26980186-4d13f5f4-4d29-11e7-9b2d-bb18a6c0ef68.png)

**Comment by mattiaerre** [comment]
very cool Idea, I think we should expandi it more thanks @gitFrey

**Comment by nickbalestra** [comment]
I got a sneak peak on @matthewdavidson and his team great logos 😍 , some also for OC, any chance you guys wanna drop some ideas here?

**Comment by jamesf3rguson** [comment]
![opencomponents](https://user-images.githubusercontent.com/8221805/27032640-c133e430-4f6d-11e7-8f46-7fe9d3cbe3f0.png)
Trying to tie it back to OpenTable through colour, font and use of circles

**Comment by jamesf3rguson** [comment]
Further aligning to OpenTable logo: 
![artboard 1 4x-80](https://user-images.githubusercontent.com/8221805/27033536-a6fca116-4f71-11e7-8050-080388d46031.jpg)

**Comment by nickbalestra** [comment]
Thank you @jamesf3rguson! I digg the last one. I still unsure if we should really tie it on a brandlevel(colors/font) to opentable

**Comment by nickbalestra** [comment]
I finally got some time to play around with some ideas. I tried to bring @gitFrey idea that we discussed earlier up to a polished final result and I must say I'm pretty happy with it.

First, why i like it:

- It's not just 2 letters ('OC') but it convey some abstract ideas, it tell a story.
- it somehow represent well what a registry of components is, and make sense both from the consumer part and both from the registry part.
- Components can have different shape, but they play well together. They share the same color cause at the end they all are opencomponents.
- It makes me want a sticker of it 😎 

and here it is

![screen shot 2017-07-23 at 7 10 58 pm](https://user-images.githubusercontent.com/389705/28501831-4f8afbe0-6fdc-11e7-9f39-8b1916c46cef.png)

**Comment by nickbalestra** [comment]
I've included the suggestion from @jamesf3rguson about using the same fontFace that we are using at OT. And some of pervious points on colors. Thanks all for the inputs!

![artboard](https://user-images.githubusercontent.com/389705/28726426-1f0c66a8-73b9-11e7-9d3e-6ebdf46760a4.png)
