### ISSUE TITLE
grunt tasks 

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#51]
It should be possible to run any cli command as grunt task as well, with the possibility of explicitly declaring all the parameters.
- [ ] Refactor cli facades in order to standardise input and output (return all the callbacks)
- [ ] Use the same facades to create a set of grunt tasks and expose them. Something like:
```js
var oc = require('oc'),
      OcGrunt = new oc.Grunt();
```

**Comment by Kadajett** [comment]
I agree that using grunt/gulp instead or in tandem to a custom cli is probably a good idea.

**Comment by matteofigus** [comment]
This has been addressed by the separate module `oc-grunt`: https://github.com/opentable/grunt-oc. Closing it.
