### ISSUE TITLE
Lerna modularisation

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#519]
There are discussions about modularising this code, and the more obvious ways are to
1) Move to opencomponents organisation the various repos
2) Create a mono-repo, possibly orchestrated by Lerna.

Benefits of 1, possibly facilitating external contributions (finding new owners for small parts of the code), and also using greenkeeper.

Benefits of 2, simplicity (test runner can test integrations between modules etc) + lerna handles all the publishing and all the sub-deps stuff.

Candidates, at least initially:
* oc-client (node)
* oc-client (browser)
* cli
* registry
* utils

**Comment by nickbalestra** [comment]
The only open issue atm with monorepo+greenkeeper is due to greenkeeper not handling nested package.json yet, but it has been flagged as "will be implemented" - https://github.com/greenkeeperio/greenkeeper/issues/139

**Comment by mattiaerre** [comment]
this is a really interesting discussion. As an Italian, my philosophy is always "Divide et impera" so in theory, I would always prefer to decouple and move a specific part/component into a specific repository. In doing so we will be forced to understand what kind of dependencies (in terms of code coupling) different parts have and see if we can simplify the contract that binds them together. On the other hand, I see great benefit in going monorepo especially given the fact that other (big) companies are implementing it w/ proficiency. I'd love to experiment myself a little bit more as I don't know this subject very well. Any resource you would recommend to read/watch?

// cc @nickbalestra @matteofigus

**Comment by mattiaerre** [comment]
## Resources

- [ ] https://danluu.com/monorepo/

**Comment by nickbalestra** [comment]
Hey Mattia, the "Divide at impera" approach still totally apply with a monorepo (fancy name for multi-package repositories), as each "divided" piece is nothing more then a package, a module to be published. The only difference is that instead of having a separate repository for each package, they sit within the same project. You can for example think of oc-hub repos as monorepo. You could handle such repos manually and orchestrate publishing/etc with some scripts, or use some libraries to help with that, i.e: [lerna](https://github.com/lerna/lerna), or [northbrook](https://github.com/northbrookjs/northbrook).

Hope that helps

**Comment by matteofigus** [comment]
Another resource I would add, is the templates we are working on now:
https://github.com/opencomponents/oc-template-jade

Still a wip but good to see how the structure is evolving (packages folder, the lerna.json, and the root's package)

**Comment by nickbalestra** [comment]
I find is also super good when you are doing "divide at impera". In the jade-template repo that Matteo mentioned you can see that I've started creating a folder "[to-be-published](https://github.com/opencomponents/oc-template-jade/tree/unified-compiler/packages/oc-template-jade-compiler/to-be-published)" those are soon-to-become-packages, and I will simply move them up in `packages` init a `package.json` for them and that's it, learna will help me publish/work with much easier as if they were each in is own repo.

**Comment by mattiaerre** [comment]
thanks for sharing this @matteofigus and @nickbalestra I think we should give lerna a go w/ the oc repo and see how we can create separate packages for core, client, cli and registry

**Comment by matteofigus** [comment]
As discussed with @nickbalestra, it could make sense to keep some modules here as monorepo, and move some others in separate repos anyways. For instance, oc-client (node) could be in its own so that we keep support for old versions of node (4, 5...) and oc-client (browser) could be in its own so that we have all the sauce labs slow tests in another repo. Things like cli and registry, instead, could stay here as lerna subrepos as it makes sense for making the code cleaner and simpler

**Comment by nickbalestra** [comment]
Yes.
I do still feel that down the road, as we optimize some repos, drop support for older versions of node also on the client, and unify/optimize test suites/CIs then we could probably converge some of those back into a monorepo, especially for interdependencies packages (ie `registry-cli-node/browser-client`)

**Comment by matteofigus** [comment]
I am closing this, as we opted for partial lerna modularisation as test in the `opencomponents` organisations and we are very happy with that.

Examples: https://github.com/opencomponents/base-templates https://github.com/opencomponents/oc-template-react https://github.com/opencomponents/storage-adapters
