### ISSUE TITLE
mime type for html files

### ISSUE THREAD

**Issue by NapoleanReigns** [opentable/oc#540]
I am trying to push a component with some html files in it. 
The mime type gets pushed to the library as `application/octect-stream`.

Can we add a mime type of html files as well.

I see the mime types defined in the below file,
https://github.com/opentable/oc/blob/master/src/utils/get-mime-type.js

**Comment by matteofigus** [comment]
sure @NapoleanReigns - would you like to make a pull request, or want us to do it?

**Comment by NapoleanReigns** [comment]
@matteofigus i can float a pull request.
