### ISSUE TITLE
Move npm to cross-spawn npm

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#593]
Currently we self-host npm inside the cli to run install commands.

It would be nice to use cross-spawn so that 
1) it could use a separate thread possibly resulting in better performance
2) it would run the command with the npm version that the user has in its machine. This brings simplicity, transparency, and enhances control
3) Consistency: we already use cross-spawn in the templates and other parts - so this would reduce the bundle too

**Comment by nickbalestra** [comment]
💯  Yess!!
