### ISSUE TITLE
Display server.js error passed to callback when doing oc dev

### ISSUE THREAD

**Issue by pbazydlo** [opentable/oc#61]
In following situation error is swallowed be oc dev repository - it would be nice if oc displayed information in some way other than `component data resolving error`:

```
module.exports.data = function(req, callback){
  var request = require('request');
  request({
    url: 'some-url',
    json: true
  },
  function(err, res, body){
    if(err || !body){
      return callback(err);
    }

    ...

    callback(null, {
      someValue: 'value'
    });
  });
};
```

**Comment by matteofigus** [comment]
When this happens, can you see anything inside the terminal?
If you are in the `dev` modality, some clues should be there. 
If you are executing this inside a registry, instead, an error callback will be handled in different ways by the registry owner.

**Comment by pbazydlo** [comment]
it happens in oc dev, terminal just says 500 and as content returns error from description (component data resolving error)
