### ISSUE TITLE
Accessing s3 over a proxy from oc-registy

### ISSUE THREAD

**Issue by NapoleanReigns** [opentable/oc#618]
I am hosting my oc-registry process as a seperate docker container over an EC2 instance in AWS and the access to s3 bucket from this instance would be via a proxy.
we have been patching our local version of oc with below piece of code change for this to work for our use case.

Patch File: src/registry/domain/s3.js

`const proxy = require('proxy-agent'); 
module.exports = function (conf) {
 const httpOptions = { timeout: conf.s3.timeout || 10000 }; 
 if (conf.s3.agentProxy) { httpOptions.agent = proxy(conf.s3.agentProxy); } 
AWS.config.update({ 
accessKeyId: conf.s3.key, 
secretAccessKey: conf.s3.secret, region: conf.s3.region, 
httpOptions, });`

this needs to be fixed here.
https://github.com/opentable/oc/blob/6651c60be60e46a6803e865074f8e632e65f489f/src/registry/domain/s3.js#L20

i think httpOptions should also consider conf.s3.agentProxy.

Thank you

**Comment by matteofigus** [comment]
I think I would be in favour of adding this optional property. Would you be able to do a PR for that?

**Comment by NapoleanReigns** [comment]
Sure, I will float a PR for considering conf.s3.agentProxy property under configuration.

Thank you.

**Comment by NapoleanReigns** [comment]
I have created a PR. 
Please Review.

Thanks

**Comment by NapoleanReigns** [comment]
Thanks Matteo.
