### ISSUE TITLE
OC should only parse dependencies specified in package.json

### ISSUE THREAD

**Issue by pbazydlo** [opentable/oc#62]
Currently oc parses all node_modeules files which is sometimes causing problems (nock) - it should only parse dependencies specified in package.json

**Comment by matteofigus** [comment]
uhm. Have you tried with `0.15.0`?

**Comment by pbazydlo** [comment]
The problem i encountered was in oc dev 0.14.6, i'll try 0.15

**Comment by pbazydlo** [comment]
in 0.15.0 i get `Missing dependencies from package.json => ["request"]` error (after npm install)

**Comment by matteofigus** [comment]
Yes. With 0.15 you need now to include the node.js dependencies (as `request`) in the package.json under the dependencies. Standard node.js. Can you try adding this?

```js
...
{
  "dependecies" {
     "request": ""
  }
}
...
```

**Comment by pbazydlo** [comment]
that's what i actually have:
```
"dependencies": {
    "request": "^2.55.0"
  },
```
