### ISSUE TITLE
Support Google Cloud Storage

### ISSUE THREAD

**Issue by kmcrawford** [opentable/oc#682]
Creating an issue for Google Cloud Storage support enhancement.

**Comment by kmcrawford** [comment]
I have a few issues with the tests (some aren't passing and I'm not sure why), need to also create new tests.  However, I have it working fine for me on Google Storage.  I also have a few questions about how to deal with a callback.. All of my questions are marked as TODOs.  I would like to create a PR, just to get some feedback.

**Comment by kmcrawford** [comment]
PR #683 created.

**Comment by kmcrawford** [comment]
Since it may be possible in the future to support many repo types.  As suggested by @nickbalestra we should decouple s3 from the current implementation as a 1st step.

Tasks:
1.) Create an interface layer to s3.js
2.) Create an interface to conf.s3 for common parts conf.s3.componentsDir, etc.  (or should common components be moved out of s3 config?)
3.) Make Error messages dynamic to support provider vs having s3 hardcoded.
4.) Update test cases to support existing config and possible new configs.

2nd step:
After above complete create new gs.js to support the same functions as s3.js.

**Comment by nickbalestra** [comment]
A branch is fine, and perhaps a little bit easier to work together on that, but I'm fine either way, just pick what you prefer. Let me know if you prefer to work on a branch as I think I'll need to give you write permission to the repo.

To add on @kmcrawford points, at the moment we have an `s3` object to hold the [configuration](https://github.com/opentable/oc/wiki/Registry). Perhaps we could abstract and rename that into something like `storage`. Inside of it we could register a module that expose all the thing needed to work, ie:
```
const registryConf: {
  ...,
  storage: {
    adapter: require('oc-s3'), // *see note
    options: {
      key: ...,
      secret: ...
    }
  },
  ...
}
```

*note: to start, I think will be easier and faster not to publish it but to simply create it and require it from the repo itself, ie:
```
adapter: require('oc/src/registry/s3') . I think this is what you refer to `s3.js`
```

**Comment by kmcrawford** [comment]
@nickbalestra I agree working on a brach would be more collaborative.  I am fine with the storage, but I wouldn't want to making breaking changes for existing users.  Just need to figure out how to still use the s3 config, but have it deprecated.

**Comment by nickbalestra** [comment]
Yes agree on the braking change.
We could simply have the s3 as the default one, so that s3 will still rely to the s3 config options, while if you have storage: {} you are actually overriding that. In this way we could keep support for the old s3 and keep the s3 code even moved into his own module within the oc core base, while for anything else you'll need to register and use the new storage api/adapter api, thoughts?

**Comment by kmcrawford** [comment]
@nickbalestra I have a branch ready to go for 1, 2, & 4.  However I do not have access to create a branch.

**Comment by kmcrawford** [comment]
Also I have to do the require like this...

```
{
  storage: {
    adapter: require('oc/src/registry/domain/s3'), 
    options: {
        key: 'my-key',
        secret: 'my-secret',
        bucket: 'my-bucket',
        region: 'us-east-1',
        path: '//s3.amazonaws.com/my-bucket/',
        componentsDir: 'components'
    }
}
```

**Comment by nickbalestra** [comment]
Now that we have a first PR for the [storage-adapters API](https://github.com/opentable/oc/pull/688) merged I'll suggest the following steps:

- move s3.js adapters to -> https://github.com/opencomponents/storage-adapters
- update documentation -> https://github.com/opentable/oc/wiki
- add google-cloud-storage adapter to -> https://github.com/opencomponents/storage-adapters

@kmcrawford what you think?

**Comment by matteofigus** [comment]
Moved the issue to the other repo.
