### ISSUE TITLE
Publishing to multiple registries

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#69]
There is a bug when publishing to 2 registries: the first publish succeeds, then the package.tar.gz is removed, then the second publish fails

Thanks @ajcw for reporting this.

**Comment by andyroyle** [comment]
@matteofigus #148 addresses part 1 (just fixes the bug)

Is part 2 actually necessary? Is it going to be a common pattern to have multiple registries connected to the same library?

**Comment by matteofigus** [comment]
True.

Purpose for the breaking change:
```js
{
  "registries": [...]
...
}
```
Should become a string if you have a unique endpoint or an object in case you want to specify public and private endpoints. This is needed so that:
* publish uses always private
* consuming uses private for server-side rendering, public for client-side rendering

```js
{
  "registry": "https://registry.com/"
...
}
// or
{
  "registries": {
    "private": "http://my-intranet.com/oc-registry",
    "public": "https://registry.my-company.com"
  }
...
}
```

**Comment by matteofigus** [comment]
So #178 introduces a breaking change for the node.js client. Registries is now an object with `clientRendering` and `serverRendering` properties. In regards of this issue I would do the same for consumers' `oc.json`:
* `oc registry add <type> <url>` is how to use the cli. Types are `clientRendering`, `serverRendering`, `publish`.
* When doing `oc publish ...` with old formatted oc.json (registries array) the cli should suggest a fix (Replace registries: [ urls] with registries: { publish: 'first'}.
* Automatically this problem will be fixed and closed.

**Comment by andyroyle** [comment]
:+1:

**Comment by matteofigus** [comment]
I don't think this is an issue anymore. The publish to multiple registries has been fixed and I don't care about changing the api for the publish.
