### ISSUE TITLE
oc-client 0.41.15 does not properly compile some dependencies

### ISSUE THREAD

**Issue by elboletaire** [opentable/oc#730]
Today I've found our CI environment failing on OC deploy, due to the following error:

![imatge](https://user-images.githubusercontent.com/153305/32321324-0ad90e58-bfc1-11e7-8749-7a7a1850730d.png)

We didn't change anything from the previous working deploy to this, but the oc-client version changed. Using oc-client 0.41.13 works as expected, but the current doesn't allow us to properly publish to the registry.

**Comment by matteofigus** [comment]
Thanks @elboletaire - I am looking into this.

**Comment by elboletaire** [comment]
BTW, is this dependency check/installreally needed? The way we work, we previously compile all the required dependencies and when we do `oc publish` we already have everything ready to be uploaded, so this is redundant for us, and even buggy as seen in #591
