### ISSUE TITLE
Dev registry and custom-templates

### ISSUE THREAD

**Issue by nickbalestra** [opentable/oc#750]
Together with @JonSchapiro we discover a bug affecting the dev registry when running non-base templates

version used: 0.42 (I guess that this will affect all the version released after #710)

to reproduce:

1. oc init test-component oc-template-react
2. oc dev . 3030
3. navigate to http://localhost:3030/test-component/~info <= All should be ok here
4. it the component endpoint on the registry http://localhost:3030/test-component will result in an error claiming that oc-template-react was not found

**Comment by matteofigus** [comment]
Can you please include node version and npm version. This definitely doesn't happen with me

**Comment by nickbalestra** [comment]
I can confirm with

```
node v6.11.3
npm v3.10.10
oc v0.42.1
```

as well as with
```
node 8.9.0
npm v4.6.1
oc v0.42.1
```

Both env resulting in the following error on step `4` of the mentioned steps to reproduce
```
{
  "code": "INTERNAL_SERVER_ERROR",
  "error": "Error requiring oc-template: \"oc-template-react\" not found",
  "name": "test-component",
  "requestVersion": ""
}
```

**Comment by matteofigus** [comment]
@nickbalestra is this still happening? I think our acceptance tests suite now covers this scenario. Should we close?

**Comment by nickbalestra** [comment]
Yes

**Comment by nickbalestra** [comment]
Seems fixed with latest
