### ISSUE TITLE
Pre-compilers on packaging

### ISSUE THREAD

**Issue by matteofigus** [opentable/oc#8]
via transpiling when packaging

https://github.com/facebook/regenerator
https://github.com/6to5/6to5

**Comment by matteofigus** [comment]
Adding native support to babel seems expensive and unrequired for now. 
The thing I would like is to convert the oc init to a more customisable way, instead of being based on pre-defined templates.

[ ] - `oc init --viewengine=jade` to specify the view engine. Default handlebars
[ ] - add in the package.json oc specification the possibility to add preprocessors (http://karma-runner.github.io/0.12/config/preprocessors.html) so that it is possible to do babel preprocessing
[ ] - add the `oc init -es6` with an automatic babel preprocessor installed

**Comment by federicomaffei** [comment]
@matteofigus did not have time to look into this lately, sorry. The es6 topic is very interesting to me, would like to pair on this when you tackle it :)

**Comment by matteofigus** [comment]
#90  =addresses this.

**Comment by matteofigus** [comment]
Closing this as well as #90
